### ISSUE TITLE
E185: Cannot find color scheme 'sourcerer'

### ISSUE THREAD

**Issue by Mahi** [xero/sourcerer.vim#1]
I can see the sourcerer.vim file in my vimfiles/bundle/sourcerer though, but vim doesn't seem to recognize it. Recognizes all other colorschemes!

**Comment by zQueal** [comment]
I've been running into this too. You can enable it via `:color sourcerer` but for whatever reason setting `colorscheme` in your .vimrc doesn't want to work.

**Comment by xero** [comment]
if the file exists in `~/.vim/colors/` it will be sourced and ready to use anywhere in your vimrc. if you're loading the file via a plugin manager from somewhere like `~/.vim/bundle/sourcerer` it appears you cannot set the colorscheme value until after you initialize it in your `.vimrc` file. i tested this with a few different colorschemes including mine, and it appears to be the case in both classic and neovim.
